# Generated by Django 5.0.4 on 2024-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_chat_receiver_alter_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
