# Generated by Django 5.0.4 on 2024-07-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_chat_is_active_siteuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
